yolo_model:

  config_file:
    name: yolov4-tiny-custom.cfg
  weight_file:
    name: yolov4-tiny-custom_best.weights
  threshold:
    value: 0.15
  detection_classes:
    names:
      - brown
      - pink
      - yellow
